//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Tests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class WebTest : global::System.Configuration.ApplicationSettingsBase {
        
        private static WebTest defaultInstance = ((WebTest)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WebTest())));
        
        public static WebTest Default {
            get {
                return defaultInstance;
            }
        }
    }
}
